import "./globals.css";
export const metadata = {
  title: "dribble_clone",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>Navbar</nav>
        <main>{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
