name: driblle_clone
run-name: Dribble Clone
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: ../Dockerfile
        with:
          node-version: "20.x"
      - name: install
        uses: npm install

      - name: build
        run: npm run build
